version: "3.7"

services:
  app:
    build: .
    command: npm run dev
    ports:
      - "3333:3333"
    depends_on:
      - db
    volumes:
      - .:/usr/app
  db:
    image: 'postgres:latest'
    container_name: "database"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - /var/lib/postgresql
    ports:
      - "5432:5432"